name: Django_Tests
on: [pull_request, push] # activates the workflow when there is a push or pull request in the repo

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pylint-django
          pip3 install -r requirements.txt
      - uses: actions/checkout@v2
      - name: Run Django unit tests
        run: |
          python3 server/manage.py test ats
      - name: Analysing the code with pylint
        run: |
          pylint --load-plugins pylint_django --django-settings-module=server.settings --rcfile=pylintrc $(git ls-files '*.py')